.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-config 1  "g-config " 
.SH NAME
g\-config \- Open interactive config editor
.SH SYNOPSIS
\fBg\-config\fR [\fB\-\-edit\fR] [\fB\-\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIKEY\fR] 
.SH DESCRIPTION
Open interactive config editor
.SH OPTIONS
.TP
\fB\-\-edit\fR
Open config file in $EDITOR
.TP
\fB\-\-path\fR
Print the path to the config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIKEY\fR]
Get a config value
