.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-show 1  "g-show " 
.SH NAME
g\-show \- Enhanced git show
.SH SYNOPSIS
\fBg\-show\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIARGS\fR] 
.SH DESCRIPTION
Enhanced git show
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIARGS\fR]
Extra arguments forwarded to git
