.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-up 1  "g-stack-up " 
.SH NAME
g\-stack\-up \- Move a stack up or down in the stack list (affects display order and PR ordering)
.SH SYNOPSIS
\fBg\-stack\-up\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Move a stack up or down in the stack list (affects display order and PR ordering)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
