.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-pr 1  "g-stack-pr " 
.SH NAME
g\-stack\-pr \- Create or update GitHub PRs for all branches in the stack
.SH SYNOPSIS
\fBg\-stack\-pr\fR [\fB\-\-open\fR] [\fB\-\-draft\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create or update GitHub PRs for all branches in the stack
.SH OPTIONS
.TP
\fB\-\-open\fR
Open PRs in browser after creating
.TP
\fB\-\-draft\fR
Draft PRs
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
