.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-switch 1  "g-stack-switch " 
.SH NAME
g\-stack\-switch \- Switch to a different stack (checks out its top branch)
.SH SYNOPSIS
\fBg\-stack\-switch\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Switch to a different stack (checks out its top branch)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Stack name to switch to
