.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-remove 1  "g-stack-remove " 
.SH NAME
g\-stack\-remove \- Remove a branch from the stack (doesn\*(Aqt delete the branch)
.SH SYNOPSIS
\fBg\-stack\-remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBRANCH\fR> 
.SH DESCRIPTION
Remove a branch from the stack (doesn\*(Aqt delete the branch)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBRANCH\fR>
Branch name to remove from stack
