//! `g workflow export` — export workflow configuration to TOML.

use anyhow::Result;
use std::fs;

use crate::cli::workflow::ExportArgs;
use crate::commands::workflow::shared::get_workflow;
use crate::commands::Ctx;
use crate::config::workflow::WorkflowsConfig;
use crate::ui;

pub fn run(_ctx: &Ctx, args: ExportArgs) -> Result<()> {
    // Get the workflow
    let workflow = get_workflow(&args.name)?;

    // Create a config with just this workflow
    let mut config = WorkflowsConfig {
        default: Some(args.name.clone()),
        ..Default::default()
    };
    config.workflows.insert(args.name.clone(), workflow);

    // Serialize to TOML
    let toml = toml::to_string_pretty(&config)?;

    // Add header comment
    let content = format!(
        "# Exported workflow: {}\n\
         # Generated by: g workflow export {}\n\
         # Import with: g workflow import <file>\n\
         \n\
         {}",
        args.name, args.name, toml
    );

    // Output
    if let Some(ref output_path) = args.output {
        fs::write(output_path, &content)?;
        ui::print_success(&format!("Exported '{}' to {}", args.name, output_path));
    } else {
        // Print to stdout
        println!("{}", content);
    }

    Ok(())
}
