.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-developer-repos 1  "g-developer-repos " 
.SH NAME
g\-developer\-repos \- List all repositories tracked in the internal database
.SH SYNOPSIS
\fBg\-developer\-repos\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all repositories tracked in the internal database
.PP
Shows every repo root path that has been seen by the tool, along with the first and most recent time it was active.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
