.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-diff 1  "g-diff " 
.SH NAME
g\-diff \- Enhanced git diff using your configured diff tool
.SH SYNOPSIS
\fBg\-diff\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIARGS\fR] 
.SH DESCRIPTION
Enhanced git diff using your configured diff tool
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIARGS\fR]
Extra arguments forwarded to git
