.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-hooks-status 1  "g-hooks-status " 
.SH NAME
g\-hooks\-status \- Show where hooks config is loaded from
.SH SYNOPSIS
\fBg\-hooks\-status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show where hooks config is loaded from
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
