.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-hooks-init 1  "g-hooks-init " 
.SH NAME
g\-hooks\-init \- Create a hooks.toml template in .g/
.SH SYNOPSIS
\fBg\-hooks\-init\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create a hooks.toml template in .g/
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
