.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-hooks-list 1  "g-hooks-list " 
.SH NAME
g\-hooks\-list \- List all configured hooks for this repository
.SH SYNOPSIS
\fBg\-hooks\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all configured hooks for this repository
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
