.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-notes-list 1  "g-notes-list " 
.SH NAME
g\-notes\-list \- List every saved note in this repo (newest first)
.SH SYNOPSIS
\fBg\-notes\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List every saved note in this repo (newest first)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
