.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-notes-show 1  "g-notes-show " 
.SH NAME
g\-notes\-show \- Show a single note by id — prints the body and its anchor
.SH SYNOPSIS
\fBg\-notes\-show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Show a single note by id — prints the body and its anchor
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

