.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-notes-delete 1  "g-notes-delete " 
.SH NAME
g\-notes\-delete \- Delete a single note by id
.SH SYNOPSIS
\fBg\-notes\-delete\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Delete a single note by id
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

