.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-notes-edit 1  "g-notes-edit " 
.SH NAME
g\-notes\-edit \- Edit the body of an existing note in `$EDITOR`
.SH SYNOPSIS
\fBg\-notes\-edit\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Edit the body of an existing note in `$EDITOR`
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

