.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-push 1  "g-push " 
.SH NAME
g\-push \- Enhanced git push with progress display
.SH SYNOPSIS
\fBg\-push\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIARGS\fR] 
.SH DESCRIPTION
Enhanced git push with progress display
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIARGS\fR]
Extra arguments forwarded to git
