.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-add 1  "g-stack-add " 
.SH NAME
g\-stack\-add \- Create a new branch on top of the current stack
.SH SYNOPSIS
\fBg\-stack\-add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBRANCH\fR> 
.SH DESCRIPTION
Create a new branch on top of the current stack
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBRANCH\fR>
Branch name to create
