.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-details 1  "g-stack-details " 
.SH NAME
g\-stack\-details \- Show the current stack with commits for each branch
.SH SYNOPSIS
\fBg\-stack\-details\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the current stack with commits for each branch
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
