.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-absorb 1  "g-stack-absorb " 
.SH NAME
g\-stack\-absorb \- Merge the current branch into the one below it in the stack
.SH SYNOPSIS
\fBg\-stack\-absorb\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Merge the current branch into the one below it in the stack
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
