.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-new 1  "g-stack-new " 
.SH NAME
g\-stack\-new \- Initialize a new stack starting from the current branch
.SH SYNOPSIS
\fBg\-stack\-new\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Initialize a new stack starting from the current branch
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Name for this stack
