.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-push 1  "g-stack-push " 
.SH NAME
g\-stack\-push \- Push all branches in the current stack
.SH SYNOPSIS
\fBg\-stack\-push\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Push all branches in the current stack
.SH OPTIONS
.TP
\fB\-\-force\fR
Force push with lease
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
