.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-stack-delete 1  "g-stack-delete " 
.SH NAME
g\-stack\-delete \- Delete a stack (and optionally its branches)
.SH SYNOPSIS
\fBg\-stack\-delete\fR [\fB\-\-branches\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Delete a stack (and optionally its branches)
.SH OPTIONS
.TP
\fB\-\-branches\fR
Also delete all branches in the stack
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Stack name
