.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-use 1  "g-workflow-use " 
.SH NAME
g\-workflow\-use \- Switch to a different workflow
.SH SYNOPSIS
\fBg\-workflow\-use\fR [\fB\-\-local\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Switch to a different workflow
.PP
Sets the active workflow for the current repository (if \-\-local) or globally.
.SH OPTIONS
.TP
\fB\-\-local\fR
Set for this repository only (saves to .g/workflow.toml)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fINAME\fR>
Workflow name to activate
