.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workspace-status 1  "g-workspace-status " 
.SH NAME
g\-workspace\-status \- Show current workspace info
.SH SYNOPSIS
\fBg\-workspace\-status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show current workspace info
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
