.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-sync 1  "g-workflow-sync " 
.SH NAME
g\-workflow\-sync \- Update branch from its source
.SH SYNOPSIS
\fBg\-workflow\-sync\fR [\fB\-\-rebase\fR] [\fB\-\-merge\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIBRANCH\fR] 
.SH DESCRIPTION
Update branch from its source
.PP
Fetches latest changes and rebases or merges from the source branch to keep the current branch up\-to\-date.
.SH OPTIONS
.TP
\fB\-\-rebase\fR
Force rebase even if merge is the default strategy
.TP
\fB\-\-merge\fR
Force merge even if rebase is the default strategy
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIBRANCH\fR]
Branch to sync (defaults to current branch)
