.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-list 1  "g-workflow-list " 
.SH NAME
g\-workflow\-list \- List all available workflows
.SH SYNOPSIS
\fBg\-workflow\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List all available workflows
.PP
Shows all defined workflows (built\-in presets and custom) with their branch types and a brief description.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
