.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-publish 1  "g-workflow-publish " 
.SH NAME
g\-workflow\-publish \- Push branch and create/update PR
.SH SYNOPSIS
\fBg\-workflow\-publish\fR [\fB\-\-draft\fR] [\fB\-\-no\-verify\fR] [\fB\-\-title\fR] [\fB\-\-body\fR] [\fB\-\-reviewers\fR] [\fB\-\-labels\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIBRANCH\fR] 
.SH DESCRIPTION
Push branch and create/update PR
.PP
Pushes the branch to the remote and creates a pull request if one doesn\*(Aqt exist, or updates the existing PR.
.SH OPTIONS
.TP
\fB\-\-draft\fR
Create PR as draft
.TP
\fB\-\-no\-verify\fR
Skip on_publish hooks
.TP
\fB\-\-title\fR \fI<TITLE>\fR
PR title (defaults to branch name)
.TP
\fB\-\-body\fR \fI<BODY>\fR
PR body
.TP
\fB\-\-reviewers\fR \fI<USERS>\fR
Add reviewers (comma\-separated)
.TP
\fB\-\-labels\fR \fI<LABELS>\fR
Add labels (comma\-separated)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIBRANCH\fR]
Branch to publish (defaults to current branch)
