.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-clone 1  "g-workflow-clone " 
.SH NAME
g\-workflow\-clone \- Clone a workflow with a new name
.SH SYNOPSIS
\fBg\-workflow\-clone\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> <\fINAME\fR> 
.SH DESCRIPTION
Clone a workflow with a new name
.PP
Creates a copy of an existing workflow (preset or custom) that can be modified independently.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fISOURCE\fR>
Source workflow name
.TP
<\fINAME\fR>
New workflow name
