.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-status 1  "g-workflow-status " 
.SH NAME
g\-workflow\-status \- Show workflow status of current branch
.SH SYNOPSIS
\fBg\-workflow\-status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show workflow status of current branch
.PP
Displays the current branch\*(Aqs workflow context including type, source, target, merge strategy, age, and PR status.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
