.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workspace-rename 1  "g-workspace-rename " 
.SH NAME
g\-workspace\-rename \- Rename a workspace (move directory and repair worktree)
.SH SYNOPSIS
\fBg\-workspace\-rename\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIOLD\fR> <\fINEW\fR> 
.SH DESCRIPTION
Rename a workspace (move directory and repair worktree)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIOLD\fR>
Current name
.TP
<\fINEW\fR>
New name
