.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-init 1  "g-workflow-init " 
.SH NAME
g\-workflow\-init \- Initialize workflow configuration
.SH SYNOPSIS
\fBg\-workflow\-init\fR [\fB\-\-local\fR] [\fB\-\-preset\fR] [\fB\-\-no\-interactive\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Initialize workflow configuration
.PP
Sets up the workflow system for first use. With \-\-local, creates a .g/ folder in the repository for team\-shared configuration.
.SH OPTIONS
.TP
\fB\-\-local\fR
Create .g/ folder in repository for team\-shared config
.TP
\fB\-\-preset\fR \fI<PRESET>\fR
Use a preset as starting point
.TP
\fB\-\-no\-interactive\fR
Skip interactive setup
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
