.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH g-workflow-edit 1  "g-workflow-edit " 
.SH NAME
g\-workflow\-edit \- Edit an existing workflow
.SH SYNOPSIS
\fBg\-workflow\-edit\fR [\fB\-\-raw\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
Edit an existing workflow
.PP
Opens the workflow configuration in your editor ($EDITOR) for direct modification.
.SH OPTIONS
.TP
\fB\-\-raw\fR
Edit raw TOML in $EDITOR
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fINAME\fR]
Workflow name to edit
